//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizWebApplication.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_questions
    {
        public int q_id { get; set; }

        [Display(Name ="Question")]
        [Required(ErrorMessage ="*")]
        public string q_text { get; set; }
        [Display(Name = "Question A")]
        [Required(ErrorMessage = "*")]
        public string QA { get; set; }
        [Display(Name = "Question B")]
        [Required(ErrorMessage = "*")]
        public string QB { get; set; }
        [Display(Name = "Question C")]
        [Required(ErrorMessage = "*")]
        public string QC { get; set; }
        [Display(Name = "Question D")]
        [Required(ErrorMessage = "*")]
        public string QD { get; set; }
        [Display(Name = "Question Answer")]
        [Required(ErrorMessage = "*")]
        public string QCorrectAns { get; set; }
        [Display(Name = "Select Category")]
        [Required(ErrorMessage = "*")]
        public Nullable<int> q_fk_catid { get; set; }
        

        public virtual tbl_category tbl_category { get; set; }
    }
}
